# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	# Every Vagrant virtual environment requires a box to build off of.
	config.vm.box = "oracle64-32.box"
	config.vm.box_url = "https://dl.dropbox.com/sh/yim9oyqajopoiqs/cx4lB6NnZU/oracle64-32.box"
	config.vm.network :private_network, ip: "192.168.33.10"
	config.vm.provider "virtualbox" do |v|
	  v.gui = false
	  v.name = "hadoop-single-node"
	end

end
